CREATE TYPE "public"."poi_type" AS ENUM (
    'accessible_entrance'
);

CREATE OR REPLACE FUNCTION "public"."handle_new_user"() RETURNS "trigger"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  insert into public.profiles (id, display_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$;


CREATE OR REPLACE FUNCTION "public"."insert_avoidance_area"("p_name" "text", "p_wkt" "text") RETURNS "uuid"
    LANGUAGE "sql"
    AS $$
  insert into public.avoidance_areas (
    name,
    boundary
  )
  values (
    p_name,
    ST_GeomFromText(p_wkt, 4326)
  )
  returning id;
$$;

CREATE TABLE IF NOT EXISTS "public"."avoidance_area_reports" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "avoidance_area_id" "uuid",
    "title" "text",
    "description" "text",
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid" DEFAULT "auth"."uid"()
);

CREATE TABLE IF NOT EXISTS "public"."avoidance_areas" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "name" "text",
    "boundary" "extensions"."geometry"(Polygon,4326) NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"(),
    "boundary_geojson" "jsonb" GENERATED ALWAYS AS (("extensions"."st_asgeojson"(("boundary")::"extensions"."geometry"))::"jsonb") STORED,
    "description" "text"
);

CREATE TABLE IF NOT EXISTS "public"."pois" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "poi_type" "public"."poi_type" NOT NULL,
    "metadata" "jsonb" NOT NULL,
    "location" "extensions"."geography" NOT NULL,
    "location_geojson" "jsonb" GENERATED ALWAYS AS (("extensions"."st_asgeojson"(("location")::"extensions"."geometry"))::"jsonb") STORED,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" NOT NULL,
    "display_name" "text",
    "avatar_url" "text",
    "updated_at" timestamp with time zone DEFAULT "now"() NOT NULL
);

CREATE TABLE IF NOT EXISTS "public"."user_common_locations" (
    "id" bigint NOT NULL,
    "user_id" "uuid",
    "label" "text" NOT NULL,
    "location" "extensions"."geography" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone
);

ALTER TABLE "public"."user_common_locations" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_common_locations_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
)

CREATE TABLE IF NOT EXISTS "public"."user_navigation_preferences" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "user_id" "uuid",
    "avoid_areas" boolean DEFAULT true,
    "gradient_tolerance" numeric DEFAULT 0.05,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL
);

ALTER TABLE ONLY "public"."avoidance_area_reports"
    ADD CONSTRAINT "avoidance_area_reports_pkey" PRIMARY KEY ("id");ALTER TABLE ONLY "public"."avoidance_areas"
    ADD CONSTRAINT "avoidance_areas_pkey" PRIMARY KEY ("id");ALTER TABLE ONLY "public"."user_navigation_preferences"
    ADD CONSTRAINT "navigation_preferences_pkey" PRIMARY KEY ("id");ALTER TABLE ONLY "public"."pois"
    ADD CONSTRAINT "pois_pkey" PRIMARY KEY ("id");ALTER TABLE ONLY "public"."pois"
    ADD CONSTRAINT "pois_poi_type_metadata_location_key" UNIQUE ("poi_type", "metadata", "location");ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");ALTER TABLE ONLY "public"."user_common_locations"
    ADD CONSTRAINT "user_common_locations_pkey" PRIMARY KEY ("id");CREATE INDEX "avoidance_areas_boundary_idx" ON "public"."avoidance_areas" USING "gist" ("boundary");CREATE INDEX "pois_location_idx" ON "public"."pois" USING "gist" ("location");ALTER TABLE ONLY "public"."avoidance_area_reports"
    ADD CONSTRAINT "avoidance_area_reports_avoidance_area_id_fkey" FOREIGN KEY ("avoidance_area_id") REFERENCES "public"."avoidance_areas"("id") ON UPDATE CASCADE ON DELETE CASCADE;ALTER TABLE ONLY "public"."avoidance_area_reports"
    ADD CONSTRAINT "avoidance_area_reports_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL;ALTER TABLE ONLY "public"."avoidance_areas"
    ADD CONSTRAINT "avoidance_areas_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."profiles"("id") ON UPDATE CASCADE ON DELETE SET NULL;ALTER TABLE ONLY "public"."user_navigation_preferences"
    ADD CONSTRAINT "navigation_preferences_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;ALTER TABLE ONLY "public"."user_common_locations"
    ADD CONSTRAINT "user_common_locations_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON UPDATE CASCADE ON DELETE CASCADE;
